import type { NextPage } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

const Home: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div className='container'>
      <Head>
        <title>Nextjs Template</title>
        <meta
          name='description'
          content='Generated by a Nextjs typescript, prisma, and tailwind template'
        />
      </Head>
      <div className='p-5 grid place-items-center'>
        <span className='text-2xl'>{t('title1')}</span>
      </div>
    </div>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
}

export default Home;
